import Head from 'next/head'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faGoogle, faGithub, faDiscord } from '@fortawesome/free-brands-svg-icons';
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <section className={styles.buttons}>
          <button className={styles.google}>
            <a href="http://localhost:3000/auth/google">
              <FontAwesomeIcon icon={faGoogle} size="xs" style={{ width: '10px', marginRight: "5px" }} /> Continuar con Google  
            </a>
          </button>
          <button className={styles.github}>
            <a href="http://localhost:3000/auth/github">
              <FontAwesomeIcon icon={faGithub} size="xs" style={{ width: '10px', marginRight: "5px" }} /> Continuar con GitHub
            </a>
          </button>
          <button className={styles.discord} onClick={() => LoginHandler('discord')}>
            <a href="http://localhost:3000/auth/discord">
              <FontAwesomeIcon icon={faDiscord} size="xs" style={{ width: '10px', marginRight: "5px" }} /> Continuar con Discord
            </a>
          </button>
        </section>
      </main>
    </div>
  )
}
